//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace junjieComWebApp.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_waiver
    {
        public int waiver_id { get; set; }
        public int concessionaire_id { get; set; }
        public Nullable<System.DateTime> waiver_date { get; set; }
    
        public virtual table_concessionaire table_concessionaire { get; set; }
    }
}
