//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace junjieComWebApp.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_maintenance_order
    {
        public int maintenance_order_id { get; set; }
        public int concessionaire_id { get; set; }
        public Nullable<System.DateTime> maintenance_date { get; set; }
        public string nature_of_maintenance { get; set; }
        public string maintenance_remarks { get; set; }
    
        public virtual table_concessionaire table_concessionaire { get; set; }
    }
}
